### ISSUE TITLE
Extension installed but not recognized

### ISSUE THREAD

**Issue by viktak** [fmarzocca/Mopiqtt#1]
First of all, thanks for making this plugin. It has a lot of potential...

However, after installing it (`python3 -m pip install Mopiqtt`) it doesn't seem to do much and I get the following message in the logs:
```
Jun 03 15:18:52 chopin mopidy[1516]: WARNING  [MainThread] mopidy.config Ignoring config section 'mopiqtt' because no matching extension was found
```

Is there anything else I need to configure that I missed?

**Comment by fmarzocca** [comment]
If you are running mopidy as a service, you need to install mopiqtt as root:

`sudo python3 -m pip install Mopiqtt`
 and restart mopidy

**Comment by viktak** [comment]
Awesome, thanks for the quick reply! It works!!!

**Comment by fmarzocca** [comment]
Thank you. To update to latest version:

`sudo pip3 install -U mopiqtt`

May I suggest you to subscribe watching the Release page so that you always keep informed about new versions? Here: https://github.com/fmarzocca/Mopiqtt/releases
