### ISSUE TITLE
Config: username is not used

### ISSUE THREAD

**Issue by hirschharald** [fmarzocca/Mopiqtt#2]
Hi Fabio,

I found out, that the username of the config is not used, because you try to get "user" instead of username in the init section

class Comms:
    def __init__(
            self, frontend, host='localhost', port=1883, topic='mopidy',
            **user**=None, password=None, **kwargs):     -------  _should be username_
        """
        Configure MQTT communication client.
        frontend (MopiqttFrontend): Instance of extension's frontend.
        """
        self.frontend = frontend
        self.host = host
        self.port = port
        self.topic = topic
        self.user = **user** -------  _should be username_
        self.password = password

        . . .
best regards
Thomas

**Comment by fmarzocca** [comment]
Thank you for this "heads-up"!
I will release a bug-fix soon.
