### ISSUE TITLE
Custom topic name

### ISSUE THREAD

**Issue by viktak** [fmarzocca/Mopiqtt#3]
I was wondering if it is possible to set a different topic for the root topic name (which currently is `mopidy`). 
When there is more than one mopidy instance manged on one broker, they seem to use the same topic.
In my own projects I solve this issue by letting the user define a custom topic (which can be as elaborate as they want), then within that topic the app can create whatever structure it wants (without affecting others).
Maybe this is a request for a future release...?

**Comment by fmarzocca** [comment]
Yes, it could be held for future release. But I have never found an architecture with more than one mopidy instance and I assumed that it is quite rare or uncommon.
Thanks for your suggestion.

**Comment by fmarzocca** [comment]
Yes,
you can change the topic in your `mopidy.conf` file, in `mopiqtt` settings:

```
[mopiqtt]
host = 192.168.1.90
port = 1883
topic = mopidy
username =
password = 
```

**Comment by viktak** [comment]
Awesomeness!!!!!
