### ISSUE TITLE
Using PID to compose clientId issues in docker

### ISSUE THREAD

**Issue by gregorij89** [fmarzocca/Mopiqtt#4]
Hi, firstly thank you for your great job in creating this plugin.

I am using Mopidy and Mopiqtt in a multiroom setup alongside to snapcast, shairport etc.  That means I have to have multiple instances of this services. My setup is very similar to what [markferry](https://github.com/markferry/multizone-audio) is doing, but leveraging docker. And here comes the catch. I´ve built my own docker image for Mopidy with all the needed plugins. Every zone in my setup has its own Mopidy container. But inside the container, only one Mopidy process is running and in every container, it is getting PID=1. That means every Mopidy instance is connecting to the broker with clientid mopidy-1 and stealing the connection for the other instance, that is currently active. It took me some time to discover this, but the fix is merely easy. It is just about using something else than PID for building clientid string.

As a workaround, I´ve added two simple commands to the build sequence of my docker images:
`RUN sed -i 's/from os import getpid/import os/g' /usr/local/lib/python3.10/dist-packages/mopiqtt/mqtt.py`
`RUN sed -i 's/getpid()/os.getenv("HOSTNAME", "docker-hostname")/g' /usr/local/lib/python3.10/dist-packages/mopiqtt/mqtt.py`

By this, I am replacing the PID with a HOSTNAME, which for a container is randomly generated by docker.

I know this fix will not work for other use cases, but I want to ask you, if you can replace the PID in clientid with something random (maybe using random library from Python :) ), or make it configurable via the config file? 

Thank you in advance.

Jiri

**Comment by fmarzocca** [comment]
Thanks for reporting this.
I will have a look within following weeks.

**Comment by fmarzocca** [comment]
Fixed in release v.1.0.11
